FROM golang:1.25-alpine

WORKDIR /app

RUN apk add --no-cache docker-cli git

COPY worker-go/go.mod worker-go/go.sum ./
RUN go mod download

COPY worker-go .

RUN go build -o worker .

CMD ["./worker"]